# Generated by Django 5.0.6 on 2024-06-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.IntegerField(default=0)),
                ('users', models.IntegerField(default=0)),
                ('scorm_packages', models.IntegerField(default=0)),
                ('assignments', models.IntegerField(default=0)),
                ('resets', models.IntegerField(default=0)),
                ('status_checks', models.IntegerField(default=0)),
            ],
        ),
    ]
