# Generated by Django 4.2.13 on 2024-06-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='domains',
            field=models.TextField(blank=True, null=True),
        ),
    ]
