# Generated by Django 5.0.6 on 2024-06-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
