# Generated by Django 5.0.6 on 2024-06-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_last_name_alter_clientuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='domains',
            field=models.TextField(blank=True, null=True),
        ),
    ]
