# Generated by Django 5.0.6 on 2024-06-10 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScormAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('course_code', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('scorm_id', models.IntegerField(null=True, unique=True)),
                ('launch_url', models.URLField(blank=True, null=True)),
                ('cover_photo', models.ImageField(blank=True, default='scorm_uploads/cover_photos/default.png', null=True, upload_to='scorm_uploads/cover_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('cover_photo', models.URLField()),
                ('short_description', models.CharField(max_length=250)),
                ('long_description', models.TextField()),
                ('syncing_status', models.BooleanField(default=False)),
                ('scorm_assets', models.ManyToManyField(blank=True, to='scorm.scormasset')),
            ],
        ),
        migrations.CreateModel(
            name='ScormAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('number_of_seats', models.IntegerField(default=1)),
                ('validity_start_date', models.DateTimeField(blank=True, null=True)),
                ('validity_end_date', models.DateTimeField(blank=True, null=True)),
                ('client_scorm_file', models.FileField(blank=True, null=True, upload_to='client_scorm_files/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('scorm_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorm.scormasset')),
            ],
        ),
        migrations.CreateModel(
            name='ScormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(null=True)),
                ('message', models.TextField(null=True)),
                ('scormdir', models.TextField(null=True)),
                ('full_path_name', models.TextField(null=True)),
                ('size', models.BigIntegerField(null=True)),
                ('zippath', models.TextField(null=True)),
                ('zipfilename', models.TextField(null=True)),
                ('extension', models.CharField(max_length=10, null=True)),
                ('filename', models.TextField(null=True)),
                ('reference', models.TextField(null=True)),
                ('scorm', models.CharField(max_length=50, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='scorm.scormasset')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('scorm', 'SCORM')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('file', models.URLField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='scorm.course')),
            ],
        ),
        migrations.CreateModel(
            name='UserScormMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_url', models.URLField(blank=True, null=True)),
                ('date_assigned', models.DateTimeField(auto_now_add=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorm.scormassignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserScormStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_scorm_id', models.CharField(blank=True, max_length=255, null=True)),
                ('scorm_name', models.CharField(blank=True, max_length=255, null=True)),
                ('complete_status', models.CharField(blank=True, max_length=255, null=True)),
                ('satisfied_status', models.CharField(blank=True, max_length=255, null=True)),
                ('total_time', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.CharField(blank=True, max_length=255, null=True)),
                ('attempt', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.JSONField(blank=True, default=list, null=True)),
                ('client_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.clientuser')),
            ],
        ),
    ]