# Generated by Django 5.0.6 on 2024-06-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0002_remove_scormasset_scorm_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='scormasset',
            name='launch_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
