# Generated by Django 5.0.6 on 2024-06-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0003_scormasset_launch_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scormasset',
            name='description',
        ),
        migrations.AddField(
            model_name='scormasset',
            name='course_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scormasset',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scormasset',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
