# Generated by Django 5.0.6 on 2024-06-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0004_remove_scormasset_description_scormasset_course_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscormmapping',
            name='date_assigned',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
