# Generated by Django 5.0.6 on 2024-06-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0005_userscormmapping_date_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscormstatus',
            name='updated_at',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
