# Generated by Django 5.0.6 on 2024-06-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0008_alter_userscormstatus_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscormstatus',
            name='updated_at',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
