name: Django NuggerKrafter CMP CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' 

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}  
          username: nugget
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            /home/nugget/scripts/deploy.sh
