name: Django NuggerKrafter CMP CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}  
          username: root 
          password: ${{ secrets.DO_ACCESS_TOKEN }}
          port: 22
          script: |
            su - nugget
            cd nuggetkrafter_cmp_new/
            source env/bin/activate  
            pip install -r requirements.txt
            python manage.py collectstatic --noinput
            git pull origin main       
            python manage.py migrate   

